### PR TITLE
Enable deploying nightly doc

### LINKED ISSUE #156: Nightly doc for goblin
cc @m4b @philipc 
I think about deploying nightly doc (whenever commits pushed to master branch)
of goblin to github pages. The reason is that we could see which changes happened
visually after applying a documentation improvement PR.

### PR DESCRIPTION
**Pull request by lzutao**
Closes #156 .

Note you need to set up [GitHub person access token](https://github.com/settings/tokens)
image
then save it in [Travis settings](https://travis-ci.org/m4b/goblin/settings) under the name `GITHUB_OAUTH_TOKEN`.

### CODE REVIEW

**Comment by lzutao** [comment]
ping @m4b

**Comment by m4b** [comment]
Have to give me a few days, probably the weekend

**Comment by lzutao** [comment]
Oh, feel free to do it later.

**Comment by m4b** [comment]
I apologize for the delay I’ve been really busy; I will attempt to review this tonight and follow your instructions for setting this up, thank you very much for your work and patience here @lzutao!

**Comment by m4b** [comment]
ok I followed your instructions, lets see if this works! :)

**Pull request merged**
