### PR TITLE
elf: prevent overflow

### PR DESCRIPTION
**Pull request by jackcmay**
Fuzzier found an overflow if bad section address or size.  

- Update `check_size` to also check addr + size
- Use saturating addition to prevent overflow or a wrap-around region bound if `check_size` is not called on a created section.

### CODE REVIEW

**Comment by jackcmay** [comment]
Looks like CI is failing on something unrelated to my changes :-(

**Comment by m4b** [comment]
Yes looks like it's this: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

aside: i find it a bit sad that for nearly 4 years travis CI did not have a single CI involved regression with any of the github projects i had, and now, with **not even 1 year into github actions**, it's already breaking my code, and wasting developer time upgrading to some new api... This does not bode well.

**Comment by jackcmay** [comment]
:-(. Should I rebase once you have applied a fix?

**Comment by m4b** [comment]
I don't have the time right now to fix the issue; maybe this weekend; i can just merge without CI if you want

**Review by m4b — APPROVED** [review]
LGTM thanks for this!

**Comment by m4b** [comment]
If you think you know how to fix, feel free to go for it in this PR, otherwise we can just merge

**Comment by m4b** [comment]
Ok i think i fixed it actually here: https://github.com/m4b/goblin/pull/244

can you rebase on top of that ?

**Comment by jackcmay** [comment]
Rebased and CI passed, woot!

**Comment by m4b** [comment]
sorrrryyyyy for spamming :D and thanks for the PR :heart:

**Comment by jackcmay** [comment]
@m4b When do you think these changes will be released so we can pick them up?

**Comment by m4b** [comment]
whoops, forgot about this, will release now!

**Comment by m4b** [comment]
ok this is released in 0.3, which rolls up several things from past few months; it's a breaking change because one part of the mach-o api changed, but otherwise it should be fine

**Pull request merged**
