### PR TITLE
elf.note: added new constants for structs: prstatus, prpsinfo, siginfo_t, mapped files.

### PR DESCRIPTION
**Pull request by xcoldhandsx**
Some constants for very useful notes.

### CODE REVIEW

**Comment by m4b** [comment]
just curious, where did you find these constants?

**Comment by xcoldhandsx** [comment]
I found these constants in readelf sources. Here is the link: https://github.com/bminor/binutils-gdb/blob/8dc433a0fb04f8fa37530d0788053dd9bea5c37d/include/elf/common.h

**Comment by m4b** [comment]
Ok we can add them, are you encountering them in the wild ?

**Comment by xcoldhandsx** [comment]
Yes. These constants are always in core dumps, representing notes for corresponding structs. I use these constants to check note types, when i try to retrieve some interesting data from core file (signal, registers and its values, process map, etc.)

**Comment by m4b** [comment]
thanks for the PR ! :)

**Pull request merged**
