### PR TITLE
Fix redundant field names in struct initialization

### PR DESCRIPTION
**Pull request by lzutao**
cc #137

### CODE REVIEW

**Comment by m4b** [comment]
For the future it’s better if these kind of fixes are rolled up into a single PR generally

**Comment by lzutao** [comment]
I'm OK with that. I just scare that the PR may get too big to be reviewed.

**Comment by m4b** [comment]
It’s fine for now, just next time :)

**Comment by lzutao** [comment]
Rebased on master.

**Comment by lzutao** [comment]
Closed in favor of #146 .

**Pull request closed without merging**
