### PR TITLE
pe: parse pkcs7 Content in certificate table

### PR DESCRIPTION
**Pull request by baloo**

### CODE REVIEW

**Comment by RaitoBezarius** [comment]
You should add a mention to the README for this new flag.

**Comment by m4b** [comment]
Hmmm, I wasn't aware you had plans to add these dependencies to goblin. So in general, this crate is _extremely_ conservative when it comes to dependencies, and none have been added for about 4-5 years, and the ones it does have I'm in control of or will never change, like adding more dependencies (or if it does, i'll just delete the dep, e.g. plain). It's going to take some good convincing why this needs to be *in goblin itself*, and why the user can't just call this function themselves on the raw bytes. In general, for more sophisticated structures like this, in this crate I've generally sided on the fact that it's not goblin's job to parse this unless it has to. And in this PR I don't see any reason why it has to (e.g., the user can just call this).
Anyway, that's the general stance, apologies in advance if that's disappointing :)

**Comment by baloo** [comment]
This is less of an issue here than it is in #358 I'll reply there

**Comment by baloo** [comment]
Can implement this in a sub-crate. Let me know if you want to get involved, or retain control over such a subcrate.

**Pull request closed without merging**
