### PR TITLE
Add support for Codeview PDB 2.0 debug directory format

### PR DESCRIPTION
**Pull request by joschock**
Adds support for Codeview PDB 2.0 debug directory format.

### CODE REVIEW

**Review by m4b — APPROVED** [review]
how hard would it be to add a test?

**Comment by joschock** [comment]
> how hard would it be to add a test?

Is there a test for the existing codeview7 support? I poked a bit, but I didn't see one - but if so, it would be pretty straightforward to extend/modify for CV2. Otherwise, it's slightly more work. If desired, I could push up a subsequent PR with a test...

**Comment by joschock** [comment]
@m4b - any objections to merging this as is? Or would you like me to push a test first?

**Comment by m4b** [comment]
note: breaking change

tests for this would be nice at some point

**Comment by m4b** [comment]
released in 0.9.0

**Pull request merged**
