### PR TITLE
build: add Github Actions template

### PR DESCRIPTION
**Pull request by lzutao**
It works on my fork: https://github.com/lzutao/goblin/commit/6221707f01f1b45f4fe160ed5c57cd2559811300/checks?check_suite_id=384422473

### CODE REVIEW

**Comment by m4b** [comment]
What does this do exactly ? (I’m not familiar with GitHub actions template)

**Comment by lzutao** [comment]
It add another CI service beside Travis.
Some advantages of github actions:
* It's free and parallel job for open repositoy
* It's fast in my opinion.

**Comment by m4b** [comment]
Cool, is there a CI button to add to readme ?

**Comment by m4b** [comment]
And do I have to enable something to get it running on this repo ?

**Comment by lzutao** [comment]
No, you don't. We just have to merge the template.

**Comment by lzutao** [comment]
> Cool, is there a CI button to add to readme ?

There are documentations about that: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository

Do you want me to add it to README file?

**Comment by m4b** [comment]
So you want to switch from Travis or add another ci job, in addition to Travis ? And will this block master while it runs ?

Just wondering what benefit would we gain by having two ci jobs ?

**Comment by lzutao** [comment]
Okay. I removed the Travis config. 

> And will this block master while it runs ?

I don't get what you mean here.

**Comment by m4b** [comment]
@lzutao the readme doesn't have a nice build.passing badge like travis had, is that normal?

**Comment by lzutao** [comment]
I will fix it later

**Comment by m4b** [comment]
Cool thanks! And thanks for fixing this up and making github actions template work :)

**Pull request merged**
