### PR TITLE
 Fix issue #309 - Advance offset by string table field size

### PR DESCRIPTION
**Pull request by track-5**
Fixes issue #309 

There's a bug in master where the code ends up misreading the symbol table because we don't advance the offset prior to reading the strings.

This change fixes the issue by adding the correct value to the offset and also includes a unit test that covers this case.

### CODE REVIEW

**Review by m4b — APPROVED** [review]
this is great thank you! I think this is a longstanding bug/irritation you've fixed, much appreciated!

**Comment by m4b** [comment]
@track-5 looks like it needs a rustfmt; you can also add `#[rustfmt::skip]` to that test block of bytes, since it doesn't need to be formatted.

**Comment by track-5** [comment]
@m4b my bad! Just ran `cargo fmt` and pushed the new commit :)

**Comment by m4b** [comment]
Looks like you need to use core instead of size for sizeof

**Comment by track-5** [comment]
Done. Ran the cargo build command locally to be sure it works now:

```
P:\goblin>cargo build --no-default-features --features="pe32"
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
```

**Comment by m4b** [comment]
ok released in 0.5.2, thanks for your help!

**Pull request merged**
