### PR TITLE
elf: Non-alloc `ProgramHeader` exposes impl.

### PR DESCRIPTION
**Pull request by dancrossnyc**
* Expose more of the `ProgramHeader` implementation regardless
  of whether the `alloc` feature is enabled.  For example,
  `ProgramHeader::from_raw_parts` is a wrapper around
  `core::slice::from_raw_parts` that has `alloc` dependency.
* Run `cargo fmt`.

Based on an internal patch by Keith Wesolowski (@wesolows).

Signed-off-by: Dan Cross <cross@oxidecomputer.com>

### CODE REVIEW

**Comment by dancrossnyc** [comment]
This is really #305, which I accidentally closed but could not get to reopen. Sigh.

**Review by m4b — APPROVED** [review]
LGTM, thanks!

**Comment by m4b** [comment]
ok released in 0.5.2, thanks for your help!

**Comment by dancrossnyc** [comment]
Thanks!

**Pull request merged**
